language: node_js

node_js:
    - "stable"

install:
    - npm ci

script:
    - npm run build
    - npm run test:coverage

after_success:
    - npm run test:report

cache:
    directories:
        - "node_modules"
